### PR TITLE
test f added

### PR DESCRIPTION
**Pull request by farrahso**
added text file "test f"

### CODE REVIEW

**Comment by KaiBizAnalytics** [comment]
You made it!

**Comment by lindsay-fredrick** [comment]
Great! Now try adding a second file and adding it to this pull request. Once that's done you can merge it in!

**Comment by farrahso** [comment]
Added .txt "test f2".

**Review by lindsay-fredrick — APPROVED** [review]
Great - go ahead and do a full merge now :)

**Review by KaiBizAnalytics — APPROVED** [review]

**Pull request merged**
